In this notebook we are going to cover some of the most fundamental concepts of tensors using tensorflow.

More Specially,

*intoduction to tensors

*getting information from tensors

*manipulating tensors

*tensors & numpy

*using tf.fuunction speed uo the process

*using GPU with tensors

*Eercise Yourself

#introduction tesors



In [91]:
#import Tensorflow
import tensorflow as tf
print(tf.__version__)


2.5.0


In [92]:
#Creating tensors with tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [93]:
#check the number of dimntions(ndim stands for num of dimwntions)
scalar.ndim


0

In [94]:
#create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [95]:
#check the dimetion of the vector
vector.ndim


1

In [96]:
#craete a metrix
matrix =tf.constant([[10,7],
                     [7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [97]:
matrix.ndim

2

In [98]:
#craete a anothe matrix 
another_matrix =tf.constant([[10.,7.],
                             [3.,2.],
                             [8.,9.]],dtype=tf.float16) #specify the data typpew with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [99]:
another_matrix.ndim

2

In [100]:
#lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [101]:
tensor.ndim

3

What we created so far

*scalar = a single number

*vector = a number with direction (wind speed)

*matrix = a 2 dimentional array of numbers

*tensor = an n dimentional array of number 

Creating Tensors with tf Variabel

In [102]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [103]:
#craete Same Tensor with tf.Variable()
changeable_tensor =tf.Variable([10,7])
unchangeable_tensor =tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [104]:
# #Let's Try chnage on of the elements in our chnagble Tensor
# changeable_tensor[0] =7
# changeable_tensor

In [105]:
#try .assign()
changeable_tensor[0].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [106]:
#Let's Try our unchnagble Tensor
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

##Creating Random Tensors

Creating a random arbitory size of Tensors

In [107]:
#craete random and same tensors
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1,random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

###Shuffle The Order Of Elements in the Tensor

In [108]:
#shuffe the tensor with the inherient order 
not_shuffled =tf.constant([[10,7],
                          [3,4],
                          [2,5]])




tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [109]:
# #shuffle the tensor
# tf.random.set_random_seed(42)
# tf.random.shuffle(not_shuffled,seed=42)

In [110]:
#shuffe the tensor with the inherient order 
not_shuffled =tf.constant([[10.0,7,5],
                          [3.,2,4],
                          [3.,1,4],
                          [5.,3,4],
                          [6.,7,4],
                          [8.,5,9]])

not_shuffled

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[10.,  7.,  5.],
       [ 3.,  2.,  4.],
       [ 3.,  1.,  4.],
       [ 5.,  3.,  4.],
       [ 6.,  7.,  4.],
       [ 8.,  5.,  9.]], dtype=float32)>

In [111]:
print(tf.random.set_seed)
tf.random.shuffle(not_shuffled)

<function set_seed at 0x7fde58dbb5f0>


<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[ 3.,  1.,  4.],
       [ 6.,  7.,  4.],
       [ 8.,  5.,  9.],
       [ 5.,  3.,  4.],
       [ 3.,  2.,  4.],
       [10.,  7.,  5.]], dtype=float32)>

It looks like our shuffle tensors in the same order  ,We need to use global and Oprtaional level random seed initilized.

In [112]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

# <tf.Tensor: shape=(6, 3), dtype=float32, numpy=
# array([[ 5.,  3.,  4.],
#        [ 6.,  7.,  4.],
#        [ 3.,  2.,  4.],
#        [ 8.,  5.,  9.],
#        [ 3.,  1.,  4.],
#        [10.,  7.,  5.]], dtype=float32)>

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[ 5.,  3.,  4.],
       [ 6.,  7.,  4.],
       [ 3.,  2.,  4.],
       [ 8.,  5.,  9.],
       [ 3.,  1.,  4.],
       [10.,  7.,  5.]], dtype=float32)>

##Other Ways to make Tensors

In [113]:
#create tensor of ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [114]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

###Turn Numpy Arrays into tensors

main Differences between numpy and tensors is that tensors can run on the gpu that is faster than numpy

In [115]:
#you can turn numpy array into tensors
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)


In [116]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [117]:
#turn numpy into tensors
A=tf.constant(numpy_A)
B=tf.constant(numpy_A,shape=(2,1,3,4))

A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 1, 3, 4), dtype=int32, numpy=
 array([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]]],
 
 
        [[[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]], dtype=int32)>)

In [118]:
A.ndim,B.ndim

(1, 4)

Getting Information From Tensors,Dealing with tenosors you need following attributes,


*shape

*rank

*dimention

*size

In [119]:
#craete a rank 3 tensor
rank_4_tensor =tf.zeros(shape=(2,3,4,5))
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [120]:
rank_4_tensor.ndim

4

In [121]:
rank_4_tensor.ndim,rank_4_tensor.shape,tf.size(rank_4_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [122]:
#get varioues attributed of our tensor

print("Datatypes of every Elemnt :",rank_4_tensor.dtype)
print("Number Of Dimnetions :",rank_4_tensor.ndim)
print("Shape of the Tensor:",rank_4_tensor.shape)
print("Elemnts along 0 axis :",rank_4_tensor.shape[0])
print("Elemnts Along last axis :",rank_4_tensor.shape[-1])
print("Total no of Elemnts :",tf.size(rank_4_tensor))
print("Total no of Elemnts :",tf.size(rank_4_tensor).numpy())


Datatypes of every Elemnt : <dtype: 'float32'>
Number Of Dimnetions : 4
Shape of the Tensor: (2, 3, 4, 5)
Elemnts along 0 axis : 2
Elemnts Along last axis : 5
Total no of Elemnts : tf.Tensor(120, shape=(), dtype=int32)
Total no of Elemnts : 120


###Indexing Tensords

indexing can be done to the tensors

In [123]:
#get the first two elemnts in the tensors
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [124]:
#get the first element from each dimntion from each index except final
rank_4_tensor[:1,:1,:1] 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [125]:
#Create a rank 2 tensor
rank_2_tensor=tf.zeros([2,2])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [126]:
rank_2_tensor.shape

TensorShape([2, 2])

In [127]:
rank_2_tensor.ndim

2

In [128]:
#get the last item of each of the row
rank_2_tensor[:,-1]


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [129]:
# Adding extra dimntion to tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [130]:
rank_3_tensor.shape


TensorShape([2, 2, 1])

In [131]:
#Alternativ to tf.nexaxis()
tf.expand_dims(rank_2_tensor,axis=-1)


<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [132]:
rank_2_tensor.shape

TensorShape([2, 2])

In [133]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]]], dtype=float32)>

###Manipulating Tensors

basic operations





In [134]:
#You can add values to a tensor using addition operator

tensor =tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [135]:
#original tensor unchnged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [136]:
#multiplication
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [137]:
#substarction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [138]:
#we can use tenserflow buit in fucntion
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [139]:
tf.add(tensor,43)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[53, 50],
       [46, 47]], dtype=int32)>

###Matrix Multiplication

two rules in the matrix multiplication

1.inner dimentions mmust match

2.result is the inner dimnetions

In [140]:
#Matrix Multiplication on Teserflow
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [141]:
tf.matmul(tensor,tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [142]:
tensor*tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [143]:
matrix_1 =tf.constant([[1,2,5],
                       [7,2,1],
                       [3,3,3]])

matrix_2 =tf.constant([[3,5],
                       [6,7],
                       [1,8]])

matrix_1,matrix_2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [144]:
tf.matmul(matrix_1,matrix_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [145]:
#matrix multiplication with python operator
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [146]:
matrix_1@matrix_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [147]:
#create a tensor with (3,2)
X =tf.constant([[1,2],
                [4,5],
                [7,8]])
#create a tensor with (3,2)
Y =tf.constant([[7,8],
                [9,10],
                [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 5],
        [7, 8]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [148]:
# #try to multiply tesors
# tf.matmul(X,Y)

In [149]:
#transpose the matrix to multilply
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 68,  86, 104],
       [113, 143, 173]], dtype=int32)>