In this notebook we are going to cover some of the most fundamental concepts of tensors using tensorflow.

More Specially,

*intoduction to tensors

*getting information from tensors

*manipulating tensors

*tensors & numpy

*using tf.fuunction speed uo the process

*using GPU with tensors

*Eercise Yourself

#introduction tesors



In [1]:
#import Tensorflow
import tensorflow as tf
print(tf.__version__)


2.5.0


In [2]:
#Creating tensors with tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check the number of dimntions(ndim stands for num of dimwntions)
scalar.ndim


0

In [4]:
#create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check the dimetion of the vector
vector.ndim


1

In [6]:
#craete a metrix
matrix =tf.constant([[10,7],
                     [7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
#craete a anothe matrix 
another_matrix =tf.constant([[10.,7.],
                             [3.,2.],
                             [8.,9.]],dtype=tf.float16) #specify the data typpew with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
#lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we created so far

*scalar = a single number

*vector = a number with direction (wind speed)

*matrix = a 2 dimentional array of numbers

*tensor = an n dimentional array of number 

Creating Tensors with tf Variabel

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
#craete Same Tensor with tf.Variable()
changeable_tensor =tf.Variable([10,7])
unchangeable_tensor =tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# #Let's Try chnage on of the elements in our chnagble Tensor
# changeable_tensor[0] =7
# changeable_tensor

In [15]:
#try .assign()
changeable_tensor[0].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
#Let's Try our unchnagble Tensor
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

##Creating Random Tensors

Creating a random arbitory size of Tensors

In [17]:
#craete random and same tensors
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1,random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>)

###Shuffle The Order Of Elements in the Tensor

In [18]:
#shuffe the tensor with the inherient order 
not_shuffled =tf.constant([[10,7],
                          [3,4],
                          [2,5]])




tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [19]:
# #shuffle the tensor
# tf.random.set_random_seed(42)
# tf.random.shuffle(not_shuffled,seed=42)

In [20]:
#shuffe the tensor with the inherient order 
not_shuffled =tf.constant([[10.0,7,5],
                          [3.,2,4],
                          [3.,1,4],
                          [5.,3,4],
                          [6.,7,4],
                          [8.,5,9]])

not_shuffled

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[10.,  7.,  5.],
       [ 3.,  2.,  4.],
       [ 3.,  1.,  4.],
       [ 5.,  3.,  4.],
       [ 6.,  7.,  4.],
       [ 8.,  5.,  9.]], dtype=float32)>

In [21]:
print(tf.random.set_seed)
tf.random.shuffle(not_shuffled)

<function set_seed at 0x7f8a8818e5f0>


<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[ 3.,  1.,  4.],
       [ 3.,  2.,  4.],
       [ 6.,  7.,  4.],
       [ 5.,  3.,  4.],
       [10.,  7.,  5.],
       [ 8.,  5.,  9.]], dtype=float32)>

It looks like our shuffle tensors in the same order  ,We need to use global and Oprtaional level random seed initilized.

In [22]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

# <tf.Tensor: shape=(6, 3), dtype=float32, numpy=
# array([[ 5.,  3.,  4.],
#        [ 6.,  7.,  4.],
#        [ 3.,  2.,  4.],
#        [ 8.,  5.,  9.],
#        [ 3.,  1.,  4.],
#        [10.,  7.,  5.]], dtype=float32)>

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[ 5.,  3.,  4.],
       [ 6.,  7.,  4.],
       [ 3.,  2.,  4.],
       [ 8.,  5.,  9.],
       [ 3.,  1.,  4.],
       [10.,  7.,  5.]], dtype=float32)>

##Other Ways to make Tensors

In [23]:
#create tensor of ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [24]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

###Turn Numpy Arrays into tensors

main Differences between numpy and tensors is that tensors can run on the gpu that is faster than numpy

In [25]:
#you can turn numpy array into tensors
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)


In [26]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [27]:
#turn numpy into tensors
A=tf.constant(numpy_A)
B=tf.constant(numpy_A,shape=(2,1,3,4))

A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 1, 3, 4), dtype=int32, numpy=
 array([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]]],
 
 
        [[[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]], dtype=int32)>)

In [28]:
A.ndim,B.ndim

(1, 4)

Getting Information From Tensors,Dealing with tenosors you need following attributes,


*shape

*rank

*dimention

*size

In [29]:
#craete a rank 3 tensor
rank_4_tensor =tf.zeros(shape=(2,3,4,5))
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
rank_4_tensor.ndim

4

In [31]:
rank_4_tensor.ndim,rank_4_tensor.shape,tf.size(rank_4_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [32]:
#get varioues attributed of our tensor

print("Datatypes of every Elemnt :",rank_4_tensor.dtype)
print("Number Of Dimnetions :",rank_4_tensor.ndim)
print("Shape of the Tensor:",rank_4_tensor.shape)
print("Elemnts along 0 axis :",rank_4_tensor.shape[0])
print("Elemnts Along last axis :",rank_4_tensor.shape[-1])
print("Total no of Elemnts :",tf.size(rank_4_tensor))
print("Total no of Elemnts :",tf.size(rank_4_tensor).numpy())


Datatypes of every Elemnt : <dtype: 'float32'>
Number Of Dimnetions : 4
Shape of the Tensor: (2, 3, 4, 5)
Elemnts along 0 axis : 2
Elemnts Along last axis : 5
Total no of Elemnts : tf.Tensor(120, shape=(), dtype=int32)
Total no of Elemnts : 120


###Indexing Tensords

indexing can be done to the tensors

In [33]:
#get the first two elemnts in the tensors
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [34]:
#get the first element from each dimntion from each index except final
rank_4_tensor[:1,:1,:1] 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
#Create a rank 2 tensor
rank_2_tensor=tf.zeros([2,2])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [36]:
rank_2_tensor.shape

TensorShape([2, 2])

In [37]:
rank_2_tensor.ndim

2

In [38]:
#get the last item of each of the row
rank_2_tensor[:,-1]


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [39]:
# Adding extra dimntion to tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [40]:
rank_3_tensor.shape


TensorShape([2, 2, 1])

In [41]:
#Alternativ to tf.nexaxis()
tf.expand_dims(rank_2_tensor,axis=-1)


<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [42]:
rank_2_tensor.shape

TensorShape([2, 2])

In [43]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]]], dtype=float32)>

###Manipulating Tensors

basic operations





In [44]:
#You can add values to a tensor using addition operator

tensor =tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [45]:
#original tensor unchnged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [46]:
#multiplication
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [47]:
#substarction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [48]:
#we can use tenserflow buit in fucntion
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [49]:
tf.add(tensor,43)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[53, 50],
       [46, 47]], dtype=int32)>

###Matrix Multiplication

two rules in the matrix multiplication

1.inner dimentions mmust match

2.result is the inner dimnetions

In [50]:
#Matrix Multiplication on Teserflow
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [51]:
tf.matmul(tensor,tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [52]:
tensor*tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [53]:
matrix_1 =tf.constant([[1,2,5],
                       [7,2,1],
                       [3,3,3]])

matrix_2 =tf.constant([[3,5],
                       [6,7],
                       [1,8]])

matrix_1,matrix_2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [54]:
tf.matmul(matrix_1,matrix_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [55]:
#matrix multiplication with python operator
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [56]:
matrix_1@matrix_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [57]:
#create a tensor with (3,2)
X =tf.constant([[1,2],
                [4,5],
                [7,8]])
#create a tensor with (3,2)
Y =tf.constant([[7,8],
                [9,10],
                [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 5],
        [7, 8]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [58]:
# #try to multiply tesors
# tf.matmul(X,Y)

In [59]:
#transpose the matrix to multilply
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 68,  86, 104],
       [113, 143, 173]], dtype=int32)>

Dot Product

Matrix Multplication known as dot procduct .

YOU can perform dot product using :

  *tf.matmul()

  *tf.tenserdot()

Dot Product

Mtrix multiplication also reffered as matrix mulytiplication.

*`tf.matmul()`

*`tf.tensordot()`

In [60]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 5],
        [7, 8]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [61]:
#perform the dot product on metrix
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120, 132],
       [147, 162]], dtype=int32)>

In [62]:
#perform matrix multiplication between X and y
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 78,  87,  96],
       [129, 144, 159]], dtype=int32)>

In [63]:
#check the values of Y,and reshape X and transposed y

print("Normal y:")
print(Y,"\n")

print("Y shaped to (2,3) :")
print(tf.reshape(Y,(2,3)),"\n")

print(" y transposed :")

print(tf.transpose(Y))

Normal y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y shaped to (2,3) :
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

 y transposed :
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Genarally performing multilpication , you will transpose than reshaping the matrix rather than transpose to complete the atrix multiplication

##Changing the Datatype of the Tensor

In [64]:
#craete a new tesnsor
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [65]:
C= tf.constant([7,10])
C.dtype

tf.int32

In [66]:
#change the float32 to float16
B =tf.cast(B,dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [67]:
#change from int32 to int16
E=tf.cast(B,dtype=tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

###Aggregating Tensors

Aggregating Tensors =Condesing them from multiple values down to a saamller amount of values


In [68]:
#get the absolute values
D =tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [69]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go thourgh follwing forms of aggregation

*   Get the minimum
*   Get the Maximum
*   Get the Mean of the Tensor
*   Get the Sum of the Tensor



In [70]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 5],
        [7, 8]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [71]:
tf.minimum( X,Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)>

In [72]:
tf.maximum(X,Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [73]:
tf.reduce_mean(X),tf.reduce_mean(Y)

(<tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>)

In [74]:
tf.reduce_sum(X),tf.reduce_sum(Y)

(<tf.Tensor: shape=(), dtype=int32, numpy=27>,
 <tf.Tensor: shape=(), dtype=int32, numpy=57>)

In [75]:
import tensorflow_probability as tfp


In [76]:
x = tf.constant([[1., 2.], [3., 4.]])
tf.math.reduce_std(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.118034>

In [77]:
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [78]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)>

In [79]:
x = tf.random.normal(shape=(100, 2, 3))

# var[i, j] is the sample variance of the (i, j) batch member of x.
var = tfp.stats.variance(x, sample_axis=0)

In [80]:
tfp.stats.variance(X)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 6], dtype=int32)>

In [81]:
#change the float32 to float16
B =tf.cast(X,dtype=tf.float16)
B
tfp.stats.stddev(B)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2.45, 2.45], dtype=float16)>

In [82]:
#change the float32 to float16
C =tf.cast(Y,dtype=tf.float16)
C
tfp.stats.stddev(C)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.633, 1.633], dtype=float16)>

In [83]:
#find the varience
#change the float32 to float16
X =tf.cast(X,dtype=tf.float16)
X

tf.math.reduce_variance(X)

<tf.Tensor: shape=(), dtype=float16, numpy=6.25>

###Find the Positonal maximum and Minimun

In [84]:
#Postional maxmum
tf.math.argmax(  X)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2])>

In [85]:
#positional minimum
tf.argmin(X)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0])>

In [86]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [87]:
#find the postional maximb
tf.argmax(F)


<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [88]:
#index on largest value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [89]:
#find the max value F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [90]:
#Check the Eqlity
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [91]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

##Squeezing the Tensor(Removing all single dimentions)

In [92]:
#create a tensor to get started
tf.random.set_seed(42)
G =tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [93]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [94]:
G_squeezed=tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

##One hot Enoding

In [95]:
#craete a list of indices
some_list =[0,1,2,3]

#one hot encode the list
tf.one_hot(some_list,depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [96]:
#specify custom values for one hot ecoding
tf.one_hot(some_list,on_value="i like deep learning", off_value="i like to l=play cricket",depth=4)

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'i like deep learning', b'i like to l=play cricket',
        b'i like to l=play cricket', b'i like to l=play cricket'],
       [b'i like to l=play cricket', b'i like deep learning',
        b'i like to l=play cricket', b'i like to l=play cricket'],
       [b'i like to l=play cricket', b'i like to l=play cricket',
        b'i like deep learning', b'i like to l=play cricket'],
       [b'i like to l=play cricket', b'i like to l=play cricket',
        b'i like to l=play cricket', b'i like deep learning']],
      dtype=object)>

###Squering,Squre Root ,Log

In [97]:
#create a new tensor
H =tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [98]:
#squre it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [99]:
#find the squreroot
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [100]:
#find the log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

###Tensors and NumPy

Tenserflow interects beauifully with NumPy array

In [101]:
#create a tensor directly from numpy
J =tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [102]:
#convert or tensor back to numpy array
np.array(J) ,type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [103]:
J=tf.constant([3.])
J.numpy()[0]


3.0

In [104]:
#default types
numpy_j=tf.constant(np.array([3.,7.,10.]))
tensor_j=tf.constant([3.,7.,10.])

#check the datatypes of each
numpy_j.dtype,tensor_j.dtype

(tf.float64, tf.float32)

###Finding the Access to GPU

In [105]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [106]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [107]:
!nvidia-smi

Sat Jun  5 07:08:57 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P0    27W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

If you  have a acess to a Cuda -enabled GPU ,Tenserfloe use it whenever it possible