In this notebook we are going to cover some of the most fundamental concepts of tensors using tensorflow.

More Specially,

*intoduction to tensors

*getting information from tensors

*manipulating tensors

*tensors & numpy

*using tf.fuunction speed uo the process

*using GPU with tensors

*Eercise Yourself

#introduction tesors



In [3]:
#import Tensorflow
import tensorflow as tf
print(tf.__version__)


2.5.0


In [5]:
#Creating tensors with tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
#check the number of dimntions(ndim stands for num of dimwntions)
scalar.ndim


0

In [7]:
#create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#check the dimetion of the vector
vector.ndim


1

In [10]:
#craete a metrix
matrix =tf.constant([[10,7],
                     [7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [12]:
#craete a anothe matrix 
another_matrix =tf.constant([[10.,7.],
                             [3.,2.],
                             [8.,9.]],dtype=tf.float16) #specify the data typpew with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
another_matrix.ndim

2

In [16]:
#lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [17]:
tensor.ndim

3

What we created so far

*scalar = a single number

*vector = a number with direction (wind speed)

*matrix = a 2 dimentional array of numbers

*tensor = an n dimentional array of number 