In this notebook we are going to cover some of the most fundamental concepts of tensors using tensorflow.

More Specially,

*intoduction to tensors

*getting information from tensors

*manipulating tensors

*tensors & numpy

*using tf.fuunction speed uo the process

*using GPU with tensors

*Eercise Yourself

#introduction tesors



In [1]:
#import Tensorflow
import tensorflow as tf
print(tf.__version__)


2.5.0


In [2]:
#Creating tensors with tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check the number of dimntions(ndim stands for num of dimwntions)
scalar.ndim


0

In [4]:
#create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check the dimetion of the vector
vector.ndim


1

In [6]:
#craete a metrix
matrix =tf.constant([[10,7],
                     [7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
#craete a anothe matrix 
another_matrix =tf.constant([[10.,7.],
                             [3.,2.],
                             [8.,9.]],dtype=tf.float16) #specify the data typpew with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
#lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we created so far

*scalar = a single number

*vector = a number with direction (wind speed)

*matrix = a 2 dimentional array of numbers

*tensor = an n dimentional array of number 

Creating Tensors with tf Variabel

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
#craete Same Tensor with tf.Variable()
changeable_tensor =tf.Variable([10,7])
unchangeable_tensor =tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# #Let's Try chnage on of the elements in our chnagble Tensor
# changeable_tensor[0] =7
# changeable_tensor

In [15]:
#try .assign()
changeable_tensor[0].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
#Let's Try our unchnagble Tensor
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

##Creating Random Tensors

Creating a random arbitory size of Tensors

In [17]:
#craete random and same tensors
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1,random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

###Shuffle The Order Of Elements in the Tensor

In [18]:
#shuffe the tensor with the inherient order 
not_shuffled =tf.constant([[10,7],
                          [3,4],
                          [2,5]])




tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [36]:
tf.random.set_seed(1234)


TypeError: ignored

In [34]:
#shuffle the tensor
tf.random.set_random_seed(1)
tf.random.shuffle(not_shuffled,seed=42)

AttributeError: ignored

In [20]:
#shuffe the tensor with the inherient order 
not_shuffled =tf.constant([[10.0,7,5],
                          [3.,2,4],
                          [3.,1,4],
                          [5.,3,4],
                          [6.,7,4],
                          [8.,5,9]])

not_shuffled

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[10.,  7.,  5.],
       [ 3.,  2.,  4.],
       [ 3.,  1.,  4.],
       [ 5.,  3.,  4.],
       [ 6.,  7.,  4.],
       [ 8.,  5.,  9.]], dtype=float32)>

In [21]:
print(tf.random.set_seed)
tf.random.shuffle(not_shuffled)

42


<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[ 5.,  3.,  4.],
       [ 3.,  1.,  4.],
       [ 3.,  2.,  4.],
       [10.,  7.,  5.],
       [ 8.,  5.,  9.],
       [ 6.,  7.,  4.]], dtype=float32)>

In [28]:

# tf.random.set_seed(seed)
tf.random.shuffle(not_shuffled,seed=42)

TypeError: ignored

In [37]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

TypeError: ignored